//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmPermisos
    {
        public int codRegistro { get; set; }
        public string codForm { get; set; }
        public string carpeta { get; set; }
        public string codRol { get; set; }
        public string vista { get; set; }
        public string etiquetaMenu { get; set; }
        public string codEmpresa { get; set; }
        public string codEquipo { get; set; }
    
        public virtual AdmRol AdmRol { get; set; }
    }
}
