//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmProgAccionesFormulario
    {
        public int codRegistro { get; set; }
        public Nullable<int> codRegistroFormulario { get; set; }
        public string Accion { get; set; }
        public string creadoPor { get; set; }
        public Nullable<System.DateTime> fechaAccion { get; set; }
        public Nullable<System.TimeSpan> horaActual { get; set; }
        public string codEmpresa { get; set; }
    
        public virtual ProAdmForm ProAdmForm { get; set; }
    }
}
