//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmSitio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdmSitio()
        {
            this.AdmUsuario = new HashSet<AdmUsuario>();
        }
    
        public int codRegistro { get; set; }
        public string codSitio { get; set; }
        public string nombreSitio { get; set; }
        public string codEmpresa { get; set; }
    
        public virtual AdmEmpresa AdmEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdmUsuario> AdmUsuario { get; set; }
    }
}
