//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmUsuarioRol
    {
        public int codUsuarioRol { get; set; }
        public string codUsuario { get; set; }
        public string codRol { get; set; }
        public string codEmpresa { get; set; }
    
        public virtual AdmRol AdmRol { get; set; }
        public virtual AdmUsuario AdmUsuario { get; set; }
    }
}
