//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdmUsuario()
        {
            this.AdmUsuarioRol = new HashSet<AdmUsuarioRol>();
            this.ProRegOprEstREDA1 = new HashSet<ProRegOprEstREDA1>();
            this.ProRegOprTanASE = new HashSet<ProRegOprTanASE>();
        }
    
        public int codRegistro { get; set; }
        public string codUsuario { get; set; }
        public string contraseña { get; set; }
        public string correo { get; set; }
        public string resetPass { get; set; }
        public string codSitio { get; set; }
        public Nullable<int> activo { get; set; }
        public string codEmpresa { get; set; }
    
        public virtual AdmSitio AdmSitio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdmUsuarioRol> AdmUsuarioRol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProRegOprEstREDA1> ProRegOprEstREDA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProRegOprTanASE> ProRegOprTanASE { get; set; }
    }
}
