//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SistemaEntities : DbContext
    {
        public SistemaEntities()
            : base("name=SistemaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdmEmpresa> AdmEmpresa { get; set; }
        public virtual DbSet<AdmEstado> AdmEstado { get; set; }
        public virtual DbSet<AdmFormulario> AdmFormulario { get; set; }
        public virtual DbSet<AdmPermisos> AdmPermisos { get; set; }
        public virtual DbSet<AdmProgAccionesFormulario> AdmProgAccionesFormulario { get; set; }
        public virtual DbSet<AdmRol> AdmRol { get; set; }
        public virtual DbSet<AdmSitio> AdmSitio { get; set; }
        public virtual DbSet<AdmUnidadMedida> AdmUnidadMedida { get; set; }
        public virtual DbSet<AdmUsuario> AdmUsuario { get; set; }
        public virtual DbSet<AdmUsuarioRol> AdmUsuarioRol { get; set; }
        public virtual DbSet<PQPRODMAQUINA> PQPRODMAQUINA { get; set; }
        public virtual DbSet<ProAdmForm> ProAdmForm { get; set; }
        public virtual DbSet<ProParametro> ProParametro { get; set; }
        public virtual DbSet<ProProceso> ProProceso { get; set; }
        public virtual DbSet<ProRegOprEstREDA1> ProRegOprEstREDA1 { get; set; }
        public virtual DbSet<ProRegOprTanASE> ProRegOprTanASE { get; set; }
    }
}
