//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProParametro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProParametro()
        {
            this.ProRegOprEstREDA1 = new HashSet<ProRegOprEstREDA1>();
            this.ProRegOprTanASE = new HashSet<ProRegOprTanASE>();
        }
    
        public int codRegistro { get; set; }
        public string codParametro { get; set; }
        public string nombreParametro { get; set; }
        public Nullable<double> minimoParametro { get; set; }
        public Nullable<double> maximoParametro { get; set; }
        public string codProceso { get; set; }
        public Nullable<int> activo { get; set; }
        public string codUnidadMedida { get; set; }
        public string codEmpresa { get; set; }
    
        public virtual AdmUnidadMedida AdmUnidadMedida { get; set; }
        public virtual ProProceso ProProceso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProRegOprEstREDA1> ProRegOprEstREDA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProRegOprTanASE> ProRegOprTanASE { get; set; }
    }
}
