//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProRegOprEstREDA1
    {
        public int codRegistro { get; set; }
        public Nullable<double> valorProReg { get; set; }
        public Nullable<System.DateTime> fechaTrabajoProReg { get; set; }
        public Nullable<System.TimeSpan> horaTrabajoProReg { get; set; }
        public Nullable<System.DateTime> fechaCreaProReg { get; set; }
        public Nullable<System.DateTime> fechaModProReg { get; set; }
        public string codUsuarioCrea { get; set; }
        public string codUsuarioMod { get; set; }
        public string codParametro { get; set; }
        public Nullable<double> maximoParametro { get; set; }
        public Nullable<double> minimoParametro { get; set; }
        public string nombreUnidadMedida { get; set; }
        public Nullable<int> codRegistroFormulario { get; set; }
        public string codSitio { get; set; }
        public string codEmpresa { get; set; }
    
        public virtual AdmUsuario AdmUsuario { get; set; }
        public virtual ProAdmForm ProAdmForm { get; set; }
        public virtual ProParametro ProParametro { get; set; }
    }
}
